service: hello-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

custom:
  serverless-offline:
    noPrependStageInUrl: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get

plugins:
  - serverless-offline
